### ISSUE TITLE
cara integrasi

### ISSUE THREAD

**Issue by arrazka** [dikiwidia/fp-solution#1]
hi kak .. bisa dijelaskan step by step cara integrasinya, saya menggunakan X100-C

**Comment by wchynto** [comment]
```
use Dikiwidia\FpSolution\FingerPrint;

Route::get("/", function () {
    $ip = "192.168.1.201";
    $port = 80;
    $com_key = 2;

    $data = FingerPrint::getData($ip, $port, $com_key);
    dd($data);
});
```

saya kasih contoh penulisan di route/web.php. tinggal masukkan saja ip dari mesin dan portnya. nanti akan return data berupa array

> hi kak .. bisa dijelaskan step by step cara integrasinya, saya menggunakan X100-C
